"use client";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import Navbar from "@components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import Provider from "@components/Provider";
import "bootstrap/dist/css/bootstrap.min.css";
import { transitions, positions, Provider as AlertProvider } from "react-alert";
import AlertTemplate from "react-alert-template-basic";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} header`}>
        <Provider>
          <AlertProvider template={AlertTemplate}>
            <Navbar />
            {children}
          </AlertProvider>
        </Provider>
      </body>
    </html>
  );
}
